### PR TITLE
Enable Fully Qualified Name for Fixed avro type

### PR DESCRIPTION
**Pull request by lukasleung**
# Background

This is similar to the enum issue (https://github.com/actgardner/gogen-avro/issues/169) however affects the avro [Fixed](https://avro.apache.org/docs/current/spec.html#Fixed) type.

# What has Changed

- update GoType() for the FieldDefinition to use String() which will format properly instead of Name
- adds unit tests specifically for the Fully Qualified Name. 

---

Sample Test Failure with current version of `gogen-avro`:
```
--- FAIL: TestRoundTrip (0.00s)
    util.go:109:
        	Error Trace:	util.go:109
        	            				schema_test.go:12
        	Error:      	Not equal:
        	            	expected: []byte{0x0, 0x0, 0xff, 0xff}
        	            	actual  : []byte{0x0, 0xff, 0xff}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	-([]uint8) (len=4) {
        	            	- 00000000  00 00 ff ff                                       |....|
        	            	+([]uint8) (len=3) {
        	            	+ 00000000  00 ff ff                                          |...|
        	            	 }
        	Test:       	TestRoundTrip
    util.go:120:
        	Error Trace:	util.go:120
        	            				schema_test.go:12
        	Error:      	Received unexpected error:
        	            	cannot decode textual record "ConflictingNamespaceFixedTestRecord": cannot decode textual fixed "com.company.team.ConflictingFixedType": datum size ought to equal schema size: 2 != 1 for key: "fixedFieldOne"
        	Test:       	TestRoundTrip
```

### CODE REVIEW

**Comment by actgardner** [comment]
Thanks @lukasleung! LGTM :)

**Comment by lukasleung** [comment]
Thanks @actgardner!

Do you have a rough idea of when you would be able to cut tags for this change? 😄

**Comment by actgardner** [comment]
@lukasleung I just cut 10.2.0 with this fix :)

**Comment by lukasleung** [comment]
Much appreciated thanks!

**Pull request merged**
