### PR TITLE
feature generate a schema name function for objects

### PR DESCRIPTION
**Pull request by vladshub**
This PR generates a SchemaName function for the generated structs.

### CODE REVIEW

**Comment by vladshub** [comment]
@actgardner can you please review?

**Comment by actgardner** [comment]
This code looks fine, could you tell me a little about your use case?

**Comment by vladshub** [comment]
If in a system we get multiple messages and we want programmatically call different processors for different message types.
Since we don't use it with Kafka but with Rabbit where it is more legitimate to have one queue for service which gets messages from different exchanges.

**Comment by actgardner** [comment]
But how is gogen-avro's generated code going to know which schema to use? Like you get some bytes from Rabbit, do they all belong to one big Avro union of a bunch of record schemas?

**Comment by vladshub** [comment]
Each record will have its own schema name (the union has also a schema name that defines it)

**Comment by actgardner** [comment]
What I'm confused about is how, before you attempt to deserialize the record, you know the record name? For reference as of 1.8.2 the Avro schema includes an official way to handle this use case (a queue with multiple object schemas): http://avro.apache.org/docs/1.8.2/spec.html#single_object_encoding_spec

I would prefer to add support for the single object encoding that's in the standard than attempt to add hooks for any possible ad-hoc solution that might be out there.

**Comment by vladshub** [comment]
@actgardner sorry for the long delay in response.
We are currently using the [existing avro](http://avro.apache.org/docs/1.8.2/spec.html#single_object_encoding_spec) recommendation however not only through your library we manage a local cache of all of the Avro schemas that we have in a project. 
At boot time we query our registry to get the id of each of them from the registry then once we get a message we use that id to start the deserialization process.
For that we need currently to write something like:
```go
sr.Register("com.example.Obj1", NewObj1, DeserializeObj1) 
```
where idealy we would like to do something like this:
```go
sr.Register(NewObj1, DeserializeObj1) 
```
where for it all to work we need to have 
```go
func (*sr) Register(string schema_name, func() AvroRecord, func(r io.Reader) (AvroRecord, error))
```
since all requests to the schema registry require the name as part of the [API](https://docs.confluent.io/current/schema-registry/develop/api.html#get--subjects-(string-%20subject)-versions)

**Comment by actgardner** [comment]
Thanks for your contribution @vladshub, sorry it took a while for me to review it!

**Pull request merged**
