### PR TITLE
Configurable Compile with allowLaxNames option

### PR DESCRIPTION
**Pull request by rgalus**
Changes `Compile` and `CompileSchemaBytes` to a variadic functions that can accept multiple options that can be passed to the program. The advantage of that is better way of handing default program options and backwards compatible API.

As discussed in https://github.com/actgardner/gogen-avro/issues/137 and https://github.com/actgardner/gogen-avro/issues/112

### CODE REVIEW

**Comment by actgardner** [comment]
Hey @rgalus! This looks good, I like the idea of adding variadic options for Compile. Since this is a change to the singature of Compile I think we'll have to put it in a new major release. It might take me some time to cut a new major release but I'll include this in v9.

**Comment by actgardner** [comment]
@rgalus Sorry this has been hanging out for a long time. I don't see a new major release coming soon since there hasn't been much activity. I think as an alternative we could add new functions like `CompileSchemaBytesWithOptions` and `CompileWithOptions`, and have the old methods just call those with the default set of options? If you're OK with that change I can merge this and do a minor release.

**Comment by rgalus** [comment]
Hey @actgardner, not sure why you want to add new functions. By adding variadic options to CompileSchemaBytes it is backwards compatible and can be used as before without changing and using default options (like in the tests I wrote)

**Comment by actgardner** [comment]
Yeah sorry, on revisiting this it's fine to merge as is. Thanks for the PR!

**Pull request merged**
