### PR TITLE
Generated comment is on a single line.

### PR DESCRIPTION
**Pull request by tanis2000**
Changed the template so that the comment is right before the struct declaration instead of having newlines before and after.
This way it fixes linting and, most important, we can use goswagger to parse the model and generate OpenAPI specs automatically through those comments.

### CODE REVIEW

**Comment by actgardner** [comment]
Looks good, thanks for the PR @tanis2000!

**Comment by tanis2000** [comment]
@actgardner are you planning to release a new version of this project in the near future? I need this patch for one of the projects I'm working on and I'd prefer not to use my fork for it :)
Cheers

**Comment by actgardner** [comment]
Hey @tanis2000, I've tagged a 6.4.0 release with this and as few other features.

**Comment by tanis2000** [comment]
Thank you so much

**Pull request merged**
