### PR TITLE
make tests and examples work again

### PR DESCRIPTION
**Pull request by rogpeppe**
The tests were not passing and there was some old code
around that didn't compile. This PR fixes that so that

	go test ./...

will run cleanly.

Also apply a few other minor cleanups.

Specific changes:

- remove schema/schema_test.go - it was testing old internals, and it's not clear how to make it work again
- remove release.sh (it doesn't look like this is needed any more - the current release does not work with the `gopkg.in` import path).
- make example/container work again, and avoid file side-effects when it's run.
- simplify test.sh (no need for the explicit iteration)
- make gogen-avro produce correctly-formatted Go source
- fix incorrect format string in compiler/method.go
- all checked-in avrogen-generated files are updated to latest version's output.

### CODE REVIEW

**Comment by actgardner** [comment]
Thanks for the PR! These seem like some nice quality-of-life improvements, except CI is currently failing. Once the CI passes I'll happily merge this. I'm also open to bumping the Travis versions to some actually recent Golang versions (1.9? ewww).

**Comment by rogpeppe** [comment]
Thanks! I'll fix the tests when I get back to a keyboard. This is actually the first stage of a sequence of PRs that should migrate gogen-avro to using Go modules. If it sounds reasonable to you, the subsequent stages were:
- check in all the go-generated source code (this is standard practice in Go and means that all the tests can be run without running `go generate`. 
- change the gogen-avro import path to have a /v6 import path and add a go.mod file. The v6 suffix is needed because of the current major version number. This, unfortunately will break existing clients when they upgrade. Another possibility would be to move to v7 to signify this. WDYT?

**Comment by actgardner** [comment]
> check in all the go-generated source code (this is standard practice in Go and means that all the tests can be run without running go generate.

Wait, commit the generated code under `test/`? That would defeat the whole point of the integration tests, I'd have to see what exactly is getting committed here to say.

> change the gogen-avro import path to have a /v6 import path and add a go.mod file. The v6 suffix is needed because of the current major version number. This, unfortunately will break existing clients when they upgrade. Another possibility would be to move to v7 to signify this. WDYT?

If we're moving to Go modules we may as well go to v7. I'd like to try and follow the branching strategy described in https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher, ideally using the tool they link to automate rewriting imports for each major release. This repo will also have special considerations because the generated code will also import the major release of the library.

**Comment by rogpeppe** [comment]
> That would defeat the whole point of the integration tests

I understand that you're concerned that the integration tests must test that the actual code generation works correctly, but I think it's possible to check in the code _and_ also have integration tests that do that.

I believe that the current situation isn't quite ideal:

- because they're not checked in, the generated files have to be .gitignored, which means it's not easy to see how the generated code has been changed when the generating code changes.
- people can't run tests in the standard way - they have to run `go generate` first.
- to run the integration tests after a code change, you'll need to run `go generate` anyway, otherwise you still won't be testing the code generation part, so having the generated code unchecked in isn't really helping.

My suggestion is to check in the files, but have a test script that removes and regenerates all the generated files when it runs. Assuming the code generation is deterministic (I hope it is), that _should_ work OK.

Something like:

    rm $(git grep -l '^// Code generated by')
    go install ./cmd/...
    go generate ./...
    go test ./...

BTW I wonder if it might be nice to have some common naming scheme for the generated files so that it's clear which files are generated without the need to look for the `// Code generated by` comment (I often use a `_gen.go` suffix).

> I'd like to try and follow the branching strategy described in https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher, ideally using the tool they link to automate rewriting imports for each major release.

So you're suggesting that a `v7` branch is created and development moves to that with the `v7.0.0` release? That does sound like a sensible approach. The tool you're referring to is https://github.com/marwan-at-work/mod I presume. That might be useful - I hadn't come across it before. Interestingly, I wrote a slightly similar tool ages ago with a similar aim (https://github.com/rogpeppe/govers) but I haven't got around to updating it for Go modules yet.

Would you mind if I made the change to use Go modules in this PR (as a separate commit to keep things clean), because that would save me fixing CI for the old approach just to discard it for the new one? :)

**Comment by actgardner** [comment]
> Would you mind if I made the change to use Go modules in this PR (as a separate commit to keep things clean), because that would save me fixing CI for the old approach just to discard it for the new one? :)

Would it make sense to do modules first and fix CI there, and then rebase this onto that? That way CI on master won't ever be in a bad state.

> So you're suggesting that a v7 branch is created and development moves to that with the v7.0.0 release? That does sound like a sensible approach. The tool you're referring to is https://github.com/marwan-at-work/mod I presume. That might be useful - I hadn't come across it before. Interestingly, I wrote a slightly similar tool ages ago with a similar aim (https://github.com/rogpeppe/govers) but I haven't got around to updating it for Go modules yet

I don't have a strong attachment to marwan-at-work/mod or another tool - as long as there's some automation to handle rewriting the imports (including in the generated code), similar to what release.sh is supposed to do now.

> I understand that you're concerned that the integration tests must test that the actual code generation works correctly, but I think it's possible to check in the code and also have integration tests that do that.

This seems like a good idea, if the CI and `./test.sh` scripts do the right thing and regenerate before running tests. I think it's equally surprising if `go test ./...` doesn't work on a clean checkout, or if it tests stale generated code when someone's working on the repo.  I like the idea that we can diff the generated code in tests to see the impact of PRs.

**Comment by rogpeppe** [comment]
> Would it make sense to do modules first and fix CI there, and then rebase this onto that? That way CI on master won't ever be in a bad state.

I was thinking of just doing it all in one large PR, but I'll do it as two PRs as you suggest. It's nicer to keep the changes smaller anyway.

**Comment by actgardner** [comment]
I've made changes on master that address a bunch of these issues without adopting modules - it should be possible to `go test ./...` now. I'm going to work on module support next.

**Pull request closed without merging**
