### PR TITLE
use Go modules

### PR DESCRIPTION
**Pull request by rogpeppe**
This PR changes gogen-avro to use Go modules for dependency management.
Because gogen-avro is already tagged with a version >v1, this requires
a new import path, which is a backwardly incompatible change, so to avoid
breaking importers that are tracking master, we move to a `v7` version.

This PR will need to be retargeted as a new `v7` branch to avoid the above-mentioned
breakage.

### CODE REVIEW

**Comment by actgardner** [comment]
Thanks for the PR @rogpeppe, I'm going to merge this to the v7 branch and pull out the necessary changes on master.

**Comment by actgardner** [comment]
I attempted to merge this into a v7 branch, but I think this is the wrong way to go about it: why cut a release branch and then work backwards to put that code on master? I"m going to spend some time to try and bring these changes into master and then make a v7 release branch with module support based on master, instead of the other way around. If you're interested in structuring a new PR that way (based on master with a rewriting script to cut a major release) I would also appreciate it.

I also noticed the generated files in this branch still seemed to refer to the non-module version of gogen-avro, which caused code generated by the v7 branch to rely on master? We'll need to resolve that so that code generated with a given major release imports the correct major release.

**Comment by rogpeppe** [comment]
> I"m going to spend some time to try and bring these changes into master and then make a v7 release branch with module support based on master, instead of the other way around.

If I understand your suggestion currently, I think you might be risking breakage of users that are following master tip (i.e. anyone that's not using some kind of version pinning), because the change to be v7 is backwardly incompatible.

If that's OK with you, then maybe we can just avoid creating a `v7` branch at all and just use `master` for everything.

> I also noticed the generated files in this branch still seemed to refer to the non-module version of gogen-avro, which caused code generated by the v7 branch to rely on master? We'll need to resolve that so that code generated with a given major release imports the correct major release.

I looked and can't see that. Could you provide an example, please? 

I checked with:
```
% find . -name '*.go' | xargs grep github.com/actgardner/gogen-avro | grep -v /v7
./example/avro/primitive.go:// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
```

The example is something that I plan to fix in the next PR (#115).

**Comment by actgardner** [comment]
> If I understand your suggestion currently, I think you might be risking breakage of users that are following master tip (i.e. anyone that's not using some kind of version pinning), because the change to be v7 is backwardly incompatible.

That's an inherent risk of following the tip of master. I should be explicit about the workflow in this repo:

- all features are developed on master
- features which are backwards compatible are cherry-picked to existing major version branches
- when sufficient breaking changes accumulate on master, a new major version branch is cut

I don't know if I was sufficiently clear about that, but we need both a v7 branch for most people to follow, and a master branch that is unstable where we can develop new features.

> I looked and can't see that. Could you provide an example, please?

I haven't had a lot of bandwidth to dig into this yet - when I merged the v7 branch ended up having the tip of master in it's lockfile, and I was having trouble compiling. That's why I decided to back this out for now.

**Comment by rogpeppe** [comment]
> I don't know if I was sufficiently clear about that, but we need both a v7 branch for most people to follow, and a master branch that is unstable where we can develop new features.

FWIW I don't _think_ a v7 branch is needed until v8 is released and it's necessary to backport  features from v8 to v7. With Go modules, clients follow major versions, not branches.

BTW I see a `release/5.0` branch but not a `release/6.0` branch, although v6 has been released for a while. But perhaps those `release/*` branches aren't related to this kind of issue?

**Comment by actgardner** [comment]
Release engineering so far hasn't been very consistent - technically every release should have a tag, and a major release only needs a branch if it gets backported changes from master _after_ breaking changes have landed. Otherwise we can just tag a commit on master for a minor or pacth release.

However, doing this process in a consistent way (cutting a major release branch when a release happens and backporting changes) would introduce a lot of rigor and IMO make it easier for people to follow development.

**Pull request merged**
