### PR TITLE
Extend namespace support to struct names

### PR DESCRIPTION
**Pull request by dmlambea**
This PR makes the generator to use the namespace as part of file/struct name, in order to avoid clashes in the generated source. the first commit in the PR has a test avro schema which shows this feature.

### CODE REVIEW

**Comment by actgardner** [comment]
Hi Daniel! Thanks for your contribution. Namespace support has been a frequently requested feature and I'd love to get a fix in.

Because this could change the names of generated structs (which would break existing code when users upgrade gogen-avro), could you add a flag similar to `short-unions` (https://github.com/actgardner/gogen-avro/blob/master/gogen-avro/main.go#L18) and make the default false so users can opt into this feature?

**Comment by dmlambea** [comment]
@actgardner I've created the flag in a similar way as the others you already have. Default behaviour is now as before.

**Comment by actgardner** [comment]
Looks good, thanks for putting this together!

**Comment by dmlambea** [comment]
Mmmm I've introduced a bug while using the tests for checking and it went throught in the PR. @actgardner, I fixed it and I'm giving it a second revision along with a better support for NS (just shorter field names and an option to generate a shorter namespace prefix for types). Is it ok for you to add it all to this PR or you prefer to open a new PR?

**Comment by actgardner** [comment]
It's ok to add them here, let me know when this is ready to review again?

**Comment by dmlambea** [comment]
@actgardner I think it's ready for review.

**Comment by actgardner** [comment]
Looks good, thanks!

**Pull request merged**
